#+TITLE: RROGG-EMACS - AN EMACS CONFIGURATION
#+PROPERTY: header-args :result silent :tangle "~/.emacs.d/init.el" :eval no-export :comments org

* Intro
** Track Loading Time of rrogg-emacs

Starting Emacs has to be as quick as possible. In order to evaluate the time it
takes to load =rrogg-emacs.org=, someone has to blow the whistle and start the
stopwatch.

#+begin_src emacs-lisp
(defvar rrogg-emacs-start-time (current-time) "Time when rrogg-emacs was started")
#+end_src

* Maximize Frame

The Emacs frame is maximized at all times to make use of every pixel on the
screen.

#+begin_src emacs-lisp
(toggle-frame-maximized)
#+end_src

* Disable GUI Bar Components

Display no GUI components other than the =modline=.

#+begin_src emacs-lisp
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
#+end_src

* Hide Welcome Screen and Empty =*scratch*=

Emacs shows a splash screen at startup from which one can easily get to the
tutorial. While helpful in the beginning, this screen gets abdicable with
time. Therefore it's disabled.
Emacs also automatically loads a buffer called =*scratch*=, which serves as a
place to try out emacs lisp code or to type out some ideas. This is very helpful
as one doesn't have to think about creating a new file for every unrelated
thought. The welcome message isn't needed, so it gets disabled.

#+begin_src emacs-lisp
(setq inhibit-splash-screen t)
(setq initial-scratch-message nil)
#+end_src

* Display Current Time and Date

While I use Emacs exclusively full screen, no user interface elements like
taskbars are visible that could offer space for useful information like the
current time and date.

A solution for that is the builtin =display-time-mode=.
Once enabled, this mode displays time and date in the modeline.

A caveat of placing that info on the modeline, is information duplication. The
time will be shown on the modeline of every open buffer.
Ideally there would be only one "universal bar" that holds such universal info.

#+begin_src emacs-lisp
(setq display-time-format "%a %e %b, %H:%M")
(setq display-time-interval 60)
(setq display-time-default-load-average nil)
(add-hook 'after-init-hook #'display-time-mode)
#+end_src

* Wrap Lines at a Reasonable Width

Long lines of text are wrapped at a width of 80 characters. In order to leave
long code lines untouched, automatic line wrap is only active in =text-mode= and
modes which inherit from it, like =org-mode=.

#+begin_src emacs-lisp
(setq-default fill-column 80)
(add-hook 'text-mode-hook 'auto-fill-mode)
#+end_src

* Force a Sane Coding System

The only way to go in regards of a sane coding system for text files is utf-8.
It has to be the the default when ever possible. This provides maximal
portability and readability across operation systems and applications.
Also the Unix way of adding a new line into a text file has to be the
default. DOS uses carriage return and line feed ("\r\n") as a line ending, where
Unix uses just line feed ("\n").

#+begin_src emacs-lisp
(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8-unix)
(set-charset-priority 'unicode)
(setq default-process-coding-system '(utf-8-unix . utf-8-unix))
(setq locale-coding-system 'utf-8)
#+end_src

* Save Commands Across Sessions

Emacs doesn't have a persistent command history by default. The build-in history
gets resetted with every new Emacs session. The package =savehist= implements a
session independent history.

#+begin_src emacs-lisp
(setq savehist-file (locate-user-emacs-file "savehist"))
(setq history-length 10000)
(setq history-delete-duplicates t)
(setq savehist-save-minibuffer-history t)
(add-hook 'after-init-hook #'savehist-mode)
#+end_src

* Unique Buffer Names

Dealing with multiple files of identical name from different directories is
sometimes confusing. Working with multiple main.cpp files is one example.
The builtin =uniquify= package makes it easier to identify the files in such
scenarios.

#+begin_src emacs-lisp
(setq uniquify-buffer-name-style 'forward)
(setq uniquify-strip-common-suffix t)
(setq uniquify-after-kill-buffer-p t)
#+end_src

* Managing Buffers

By default =C-x C-b= calls the Buffer List. IBuffer is an alternative with more
functionality when it comes to manipulate the buffer list and switching
buffers.
It can filter the buffer list in various ways, execute =occur= or
=query-replace= commands straight from the list and much more.
Check =C-h m= while in IBuffer and read it's help.
A demonstration of it's capabilities can be observed in Protesilaos Stavrou's
video [[http://192.168.178.110:3000/watch?v=6KN_oSLFf-k][Emacs: introduction to IBUFFER]].

The format of IBuffer is changed so that the name column gets elided after 40
characters instead of the default 16 to make longer buffer names readable.

#+begin_src emacs-lisp
(setq ibuffer-expert t)
(setq ibuffer-display-summary nil)
(setq ibuffer-use-other-window nil)
(setq ibuffer-show-empty-filter-groups nil)
(setq ibuffer-movement-cycle nil)
(setq ibuffer-default-sorting-mode 'filename/process)
(setq ibuffer-use-header-line t)
(setq ibuffer-default-shrink-to-minimum-size nil)
(setq ibuffer-saved-filter-groups nil)
(setq ibuffer-old-time 48)
(setq ibuffer-formats
        '((mark modified read-only locked " "
                (name 40 40 :left :elide)
                " "
                (size 9 -1 :right)
                " "
                (mode 16 16 :left :elide)
                " " filename-and-process)
          (mark " "
                (name 16 -1)
                " " filename)))
(define-key global-map (kbd "C-x C-b") #'ibuffer)
#+end_src

* Package Management

Most extensions to Emacs can be loaded from archives, which are accessible via
Emacs' very own package manager =package.el=. To use this feature, =package.el=
needs to know, which archives it should use.
Out of the box, Emacs includes the =GNU ELPA= archive. It contains packages
conform with the terms of the Free Software Foundation.

To handle the package management, =package.el= has to be required early.

#+begin_src emacs-lisp
(require 'package)
#+end_src

Installing external packages that can be found in one of the Emacs Lisp Package
Archives is not an automatic process by default. The variable
=rrogg-emacs-autoinstall= has to be true in order to enable autoinstall.
A list of packages that =rrogg-emacs= tries to configure but are not installed will
be populated by the macro =rrogg-emacs-elpa-package=.
Those packages can be installed by running the function
=rrogg-emacs-install-missing-packages=.

#+begin_src emacs-lisp
(defvar rrogg-emacs-autoinstall nil
  "Control if `rrogg-emacs-elpa-package' should install packages automatically.
A value of nil will disable automatic installation of missing packages.
A non-nil value will install missing packages automatically without asking the user for consent.")

(defvar rrogg-emacs-missing-packages-list nil
  "List of package names that are required in rrogg-emacs, but currently not installed.")

(defun rrogg-emacs-install-missing-packages ()
  "Install all packages from the `rrogg-emacs-missing-packages-list'."
  (interactive)
  (when (yes-or-no-p (format "Try to install %d packages?"
                             (length rrogg-emacs-missing-packages-list)))
    (package-refresh-contents)
    (mapc (lambda (package)
            (unless (package-installed-p package)
              (package-install package)))
          rrogg-emacs-missing-packages-list)))
#+end_src

Packages that are not shipped with Emacs or are not additions from me for
standard packages, are loaded and configured via =rrogg-emacs-elpa-package=. If
those have not been installed yet, they are marked for installation by
explicitly running =rrogg-emacs-install-missing-packages= or installed
automatically if =rrogg-emacs-autoinstall= is non-nil. If the package is
installed already, it gets loaded and configured with the settings passed to the
macro.

#+begin_src emacs-lisp
(defmacro rrogg-emacs-elpa-package (package &rest body)
  "Set up PACKAGE installed from one of the `package-archives' with the rest BODY.
PACKAGE is a quoted symbol ('package) and BODY consists of balanced expressions (setq variable value)."
  `(progn
     (when (and rrogg-emacs-autoinstall
                (not (package-installed-p ,package)))
       (package-install ,package))
     (if (require ,package nil 'noerror)
         (progn ,@body)
       (display-warning 'rrogg-emacs (format "Loading package `%s' failed" ,package) :warning)
       (add-to-list 'rrogg-emacs-missing-packages-list ,package)
       (display-warning 'rrogg-emacs (format "Run `rrogg-emacs-install-missing-packages' to install all missing packages listed in `rrogg-emacs-missing-packages-list'") :warning))))
#+end_src

* Themes

The look of Emacs is defined in a theme. Custom themes usually alter e.g. the
colors used to highlight headings or code. Readability and accessibility has
highest priority. This may be to the expense of having a "stylish" looking
Emacs, but that's OK.

I found out about the =Modus= themes created by [[https://protesilaos.com][Protesilaos Stavrou]] while
watching one of his videos about Emacs. Those themes are conform with the
highest accessibility standard for color contrast between background and
foreground values (WCAG AAA).

The themes are shipped with Emacs since version =28.1=. The latest version is
also available from ELPA. The ELPA version is the one I use.

=Modus Operandi= is the light variant.
=Modus Vivendi= is the dark variant.

The themes come with a lot of options for customization. If those are used, they
need to be set prior to the loading of the theme.

#+begin_src emacs-lisp
(rrogg-emacs-elpa-package 'modus-themes
  ;; Add all customizations prior to loading the themes

  ;; Load the theme files before enabling a theme
  (modus-themes-load-themes)

  ;; Load the theme
  (modus-themes-load-vivendi))
#+end_src

* Fonts

#+begin_src emacs-lisp
(defvar rrogg-emacs-typeface-history ()
  "Minibuffer history for `rrogg-emacs-typefaces-prompt'.")

(defun rrogg-emacs-typefaces-prompt ()
  "Select installed font."
  (let ((default (nth 1 rrogg-emacs-typeface-history)))
    (completing-read
     (format "Select typeface [%s]: " default)
     (sort
      (delete-dups
       (funcall 'font-family-list))
      'string-lessp)
     nil t nil 'rrogg-emacs-typeface-history default)))

(defvar rrogg-emacs-typeface-weight-history ()
  "Minibuffer history for `rrogg-emacs-typeface-weights-prompt'.")

(defun rrogg-emacs-typeface-weights-prompt (family)
  "Select weight for font FAMILY."
  (let ((default (nth 1 rrogg-emacs-typeface-weight-history)))
    (completing-read
     (format "Select weight [%s]: " default)
     (sort (seq-uniq (mapcar (lambda (x) (elt x 3)) (x-family-fonts family))) 'string-lessp)
     nil t nil 'rrogg-emacs-typeface-weight-history default)))

(defvar rrogg-emacs-typeface-height-history ()
  "Minibuffer history for `rrogg-emacs-typeface-heights-prompt'.")

(defvar rrogg-emacs-font-heights
  '(80 85 90 95 100 105 110 120 130 140 150 160 170 180)
  "List of font heights.")

(defun rrogg-emacs-typeface-heights-prompt ()
  "Select height for font."
  (let ((default (nth 1 rrogg-emacs-typeface-height-history)))
    (string-to-number
     (completing-read
      (format "Select height [%s]: " default)
      (mapcar #'number-to-string rrogg-emacs-font-heights)
      nil nil nil 'rrogg-emacs-typeface-height-history default))))

(defun rrogg-emacs-set-face-attribute (face family weight height)
  "Set FAMILY, WEIGHT and HEIGHT for FACE."
  (internal-set-lisp-face-attribute face :family family 0)
  (internal-set-lisp-face-attribute face :weight weight 0)
  (internal-set-lisp-face-attribute face :height height 0))

(defun rrogg-emacs-set-default-font (font weight height)
  "Change `default' face family to FONT with WEIGHT and HEIGHT."
  (interactive
   (let* ((font (rrogg-emacs-typefaces-prompt))
          (weight (intern (rrogg-emacs-typeface-weights-prompt font)))
          (height (rrogg-emacs-typeface-heights-prompt)))
     (list font weight height)))
  (rrogg-emacs-set-face-attribute 'default font weight height))

(rrogg-emacs-set-face-attribute 'default "Hack" 'regular 120)
#+end_src

* Spellchecking

Checking text for spelling will typically occur for German and English.
Switching between the =aspell= dictionaries can be done via
=rrogg-emacs-spell-change-dictionary=.
=rrogg-emacs-spell= checks the active region or the word at point against the
dictionary.

#+begin_src emacs-lisp
(defvar rrogg-emacs-spell-dictionaries
  '(("EN English" . "en")
    ("DE Deutsch" . "de_DE")
    ("FR Français" . "fr"))
  "Alist of strings with dictionary descriptions and dictionary keys.
Used by `rrogg-emacs-spell-change-dictionary'.")

(defvar rrogg-emacs-spell-dictionary-hist '()
  "Input history for `rrogg-emacs-spell-change-dictionary'.")

(defun rrogg-emacs-spell-dictionary-prompt ()
  "Helper prompt to select from `rrogg-emacs-spell-dictionaries'."
  (let ((default (car rrogg-emacs-spell-dictionary-hist)))
    (completing-read
     (format "Select dictionary [%s]: " default)
     (mapcar #'car rrogg-emacs-spell-dictionaries)
     nil t nil 'rrogg-emacs-spell-dictionary-hist default)))

(defun rrogg-emacs-spell-change-dictionary (dictionary)
  "Select a DICTIONARY from `rrogg-emacs-spell-dictionaries'."
  (interactive
   (list (rrogg-emacs-spell-dictionary-prompt)))
  (let* ((key (cdr (assoc dictionary rrogg-emacs-spell-dictionaries)))
         (description (car (assoc dictionary rrogg-emacs-spell-dictionaries))))
    (ispell-change-dictionary key)
    (message "Switched dictionary to %s" (propertize description 'face 'bold))))

(defun rrogg-emacs-spell (beg end)
  "Spellcheck between BEG END or current word.

Use `flyspell-region' on the active region.  With point over a
word and no active region invoke `ispell-word'."
  (interactive "r")
  (cond
   ((use-region-p)
    (flyspell-region beg end))
   ((thing-at-point 'word)
    (call-interactively 'ispell-word))))
#+end_src

* Backup Files

Emacs automatically creates backups of files, usually in
=.emacs.d/var/backup/=. I like to locate them a little bit more obvious in the
root of the Emacs user directory. This should help me finding them easier in
case I need them.

#+begin_src emacs-lisp
(setq backup-directory-alist
      `(("." . ,(concat user-emacs-directory "backup/"))))
(setq backup-by-copying t)
(setq version-control t)
(setq delete-old-versions t)
(setq kept-new-versions 6)
(setq kept-old-versions 2)
(setq create-lockfiles nil)
#+end_src

* Magit

=magit= is a superb interface to =git=.

#+begin_src emacs-lisp
(rrogg-emacs-elpa-package 'magit
  (setq magit-define-global-key-bindings nil)
  (define-key global-map (kbd "C-c g") #'magit-status))
#+end_src

** How to Write a Good Commit Message

A good commit message follows [[https://chris.beams.io/posts/git-commit/][7 rules]]:

1. Separate subject from body with a blank line
2. Limit the subject line to 50 characters
3. Capitalize the subject line
4. Do not end the subject line with a period
5. Use the imperative mood in the subject line
6. Wrap the body at 72 characters
7. Use the body to explain what and why vs. how

For example:

#+begin_example
Summarize changes in around 50 characters or less

More detailed explanatory text, if necessary. Wrap it to about 72
characters or so. In some contexts, the first line is treated as the
subject of the commit and the rest of the text as the body. The
blank line separating the summary from the body is critical (unless
you omit the body entirely); various tools like `log`, `shortlog`
and `rebase` can get confused if you run the two together.

Explain the problem that this commit is solving. Focus on why you
are making this change as opposed to how (the code explains that).
Are there side effects or other unintuitive consequences of this
change? Here's the place to explain them.

Further paragraphs come after blank lines.

 - Bullet points are okay, too

 - Typically a hyphen or asterisk is used for the bullet, preceded
   by a single space, with blank lines in between, but conventions
   vary here

If you use an issue tracker, put references to them at the bottom,
like this:

Resolves: #123
See also: #456, #789
#+end_example

All stylistic rules can be taken care of by =magit=.
It will color characters on the summary line exceeding length of 50 red and does
the same for the second line, which should be blank.
The body of the message is wrapped at length 72.

#+begin_src emacs-lisp
(setq git-commit-summary-max-length 50)
(setq git-commit-fill-column 72)
(defun rrogg/git-commit-setup()
  (insert "#1. Capitalize the subject line
#2. Do not end the subject line with a period
#3. Use the present tense imperative mood in the subject line and body
#4. Use the body to explain what and why vs. how
#-----------------------------------------------
#If applied, this commit will …
"))
(add-hook 'git-commit-setup-hook #'rrogg-emacs-git-commit-setup)
#+end_src

* PDF

There are currently some issues with =pdf-tools-install= ([2022-07-27]).
Building the =epdfinfo= fails ([[https://github.com/politza/pdf-tools/issues/709#issuecomment-1174055858][issue]]), but pointing to the build directory
manually does work:

#+begin_example
(pdf-tools-build-server (expand-file-name (concat user-emacs-directory "elpa/pdf-tools-1.0")) nil nil nil (expand-file-name (concat user-emacs-directory "elpa/pdf-tools-1.0/server")))
#+end_example

Let's simplify that with a wrapper function around the call.

#+begin_src emacs-lisp
(defun rrogg-emacs-build-epdfinfo-manually ()
  "Builds epdfinfo for pdf-tools manually."
  (pdf-tools-build-server (expand-file-name (concat user-emacs-directory "elpa/pdf-tools-1.0")) nil nil nil (expand-file-name (concat user-emacs-directory "elpa/pdf-tools-1.0/server"))))
#+end_src

It works if one also changes the autobuild file for the server ([[https://github.com/vedang/pdf-tools/issues/102#issuecomment-1120857854][issue]]).
In =~/.emacs.d/elpa/pdf-tools-1.0/server/autobuild=, add "CXXFLAGS='-std=c++17'"
after "./configure":

#+begin_example
Before: eval "./configure -q $(quote "$prefix") && make clean && make -s || exit_fail"
After: eval "./configure CXXFLAGS='-std=c++17' -q $(quote "$prefix") && make clean && make -s || exit_fail"
#+end_example

#+begin_src emacs-lisp
(rrogg-emacs-elpa-package 'pdf-tools
  (pdf-tools-install)
  (setq-default pdf-view-display-size 'fit-page))
#+end_src

* Org Mode

#+begin_src emacs-lisp
(setq org-directory (convert-standard-filename "~/org/"))
;; general
(setq org-adapt-indentation nil)
;; tasks
(setq org-todo-keywords
      '((sequence "NEXT(n)" "WAITING(w)" "CALL(c)" "VISIT(v)" "TRAVEL(t)" "PLANNING(p)" "STARTED(s)" "HOLD(h)" "|" "DONE(d)" "CANCELLED(C)" "NOPART(N)")))
(setq org-use-fast-todo-selection 'expert)
;; IDs
(require 'org-id)
(setq org-id-link-to-org-use-id
      'create-if-interactive-and-no-custom-id)
;; capture
(setq rrogg-emacs-capture-template-task "* NEXT %?
:LOGBOOK:
:CREATED: %U
:END:
%a


")
(setq org-capture-templates `(("t" "Task" entry (file rrogg-emacs-org-default-refile-file)
                               ,rrogg-emacs-capture-template-task)))
(add-hook 'org-capture-prepare-finalize-hook #'org-id-get-create)
;; refile
(setq rrogg-emacs-org-default-refile-file (concat org-directory "refile.org")) ;; Move to seperate file, add description for describe function
(setq org-refile-targets
      '((org-agenda-files . (:maxlevel . 9))
        (nil . (:maxlevel . 9))))
(setq org-refile-use-outline-path t)
(setq org-refile-allow-creating-parent-nodes 'confirm)
(setq org-refile-use-cache t)
;; logging
(setq org-log-refile 'time)
(setq org-log-reschedule 'time)
(setq org-log-redeadline 'time)
(setq org-log-done 'time)
(setq org-log-into-drawer t)
(setq org-treat-S-cursor-todo-selection-as-state-change nil)
;; agenda
(setq org-agenda-files (directory-files-recursively org-directory "\\.org$"))
(setq org-agenda-window-setup 'current-window)
(setq org-agenda-span 'week)
(setq org-agenda-start-on-weekday 1)
(setq org-agenda-time-grid
        '((daily today require-timed)
          (0600 0800 1000 1200 1400
		1600 1800 2000 2200)
          " ....." "-----------------"))
(setq org-agenda-prefix-format
      '((agenda . " %-12:c%?-12t")
        (todo . " %i %-12:c")
        (tags . " %i %-12:c")
        (search . " %i %-12:c")))
;; code blocks
(setq org-src-window-setup 'current-window)
(setq org-confirm-babel-evaluate nil)
(setq org-src-fontify-natively t)
(setq org-src-tab-acts-natively t)
(setq org-src-preserve-indentation t)
;; key bindings
(let ((map global-map))
  (define-key map (kbd "C-c a") #'org-agenda)
  (define-key map (kbd "C-c c") #'org-capture)
  (define-key map (kbd "C-c l") #'org-store-link))
#+end_src

** Agenda

The agenda is the central dashboard showing an overview of tasks. That my be all
my work related tasks for a day, my meeting appointments for the next week or
the tasks belonging to a private project. Invoking =C-c a= anywhere in Emacs
will show the main menu of the agenda feature of Org mode.

All org files specified in the variable =org-agenda-files= contribute to the
agenda.

*** Agenda Views

How the agenda is rendered is of course customizable.
Agenda views can be saved to the =org-agenda-custom-commands= list and will be
presented as an option when calling the agenda dispatcher with =C-c a=.

The agenda setup is drawing heavily from the amazing work of [[http://doc.norang.ca/org-mode.html][Bernt Hansen]].

#+begin_src emacs-lisp :noweb yes
(setq org-agenda-custom-commands '())
(add-to-list 'org-agenda-custom-commands
             <<my-agenda>>)
(add-to-list 'org-agenda-custom-commands
             <<my-work-agenda>>)
(add-to-list 'org-agenda-custom-commands
             <<my-private-agenda>>)
#+end_src

**** My Agenda

The main agenda is a composition of multiple agenda commands. The list syntax
for a composite agenda buffer is
=(key desc (cmd1 cmd2 ...) general-settings-for-whole-set files)=.

#+begin_src emacs-lisp :tangle no :noweb yes :noweb-ref my-agenda
'(<<my-agenda-key-desc>>
  (<<my-agenda-cmd-agenda>>
   <<my-agenda-cmd-refile>>
   <<my-agenda-cmd-stuck-project>>
   <<my-agenda-cmd-project>>
   <<my-agenda-cmd-project-next>>
   <<my-agenda-cmd-standalone>>
   <<my-agenda-cmd-project-plan>>
   <<my-agenda-cmd-waiting>>))
#+end_src

The agenda can be called by pressing =key= when on the agenda dispatcher. The
complete key command is =C-c a SPC=.
A description of the view is passed to the agenda dispatcher via =desc=.

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-key-desc
" " "My Agenda"
#+end_src

***** Daily/Weekly Agenda

The daily/weekly agenda is at the top of the buffer.
It is spawned by a non-matching agenda command with syntax =(cmd "" settings)=.

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-agenda
(agenda "")
#+end_src

***** Headings to Refile

Headings that have been captured but still need to be refiled, appear below the
daily/weekly agenda.
There is an agenda command =tags= that matches tags/properties/todos in all
agenda files. General syntax for matching agenda commands is =(cmd "match"
settings files)=.

#+begin_src emacs-lisp :tangle no :noweb yes :noweb-ref my-agenda-cmd-refile
(<<my-agenda-cmd-refile-cmd-match>>
      <<my-agenda-cmd-refile-settings>>)
#+end_src

All of the headings to be shown here have a tag =:REFILE:= assigned to them, so
it will search for this tag.

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-refile-cmd-match
tags "REFILE"
#+end_src

The way the matching headings are presented can be adjusted using settings.
The header of the refile section is changed.
Subtrees of a match are skipped in order to prevent a potentially very long list
of matches.

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-refile-settings
((org-agenda-overriding-header "Headings to Refile")
 (org-tags-match-list-sublevels nil))
#+end_src

***** Stuck Projects
:PROPERTIES:
:ID:       ca4c4ff1-0d86-460d-bd68-ec5f96d549b3
:END:

A stuck project is one that does not have any subtask (or subproject) that can
be worked on right now. To unstuck a project, at least one of its tasks has to
be in a =NEXT= state.

#+begin_src emacs-lisp :tangle no :noweb yes :noweb-ref my-agenda-cmd-stuck-project
(<<my-agenda-cmd-stuck-project-cmd-match>>
      <<my-agenda-cmd-stuck-project-settings>>)
#+end_src

Exclude projects that are on hold or cancelled.

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-stuck-project-cmd-match
tags-todo "/!-HOLD-CANCELLED-PLANNING"
#+end_src

Projects can't be found with todo-states alone, because I don't have a dedicated
state for them.
Therefore the function [[id:8dc94898-0f38-4aee-b1be-db569f3879a3][=rrogg/skip-non-stuck-projects=]] is called, which decides
which headings to skip for being displayed in this section on the agenda.

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-stuck-project-settings
((org-agenda-overriding-header "Stuck Projects")
 (org-agenda-skip-function 'rrogg/skip-non-stuck-projects))
#+end_src

***** Projects

Projects that can be worked on are listed in this section. Those projects have
at least one task in =NEXT= state, that is unblocked and can be worked on.

#+begin_src emacs-lisp :tangle no :noweb yes :noweb-ref my-agenda-cmd-project
(<<my-agenda-cmd-project-cmd-match>>
      <<my-agenda-cmd-project-settings>>)
#+end_src

Cancelled and on-hold projects are not displayed.
Also projects still in planning phase are excluded.

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-project-cmd-match
tags-todo "/!-HOLD-CANCELLED-PLANNING"
#+end_src

The skip function that identifies projects is [[id:6faa31dc-43a0-447a-88d0-fffbe14a3cb0][=rrogg/skip-non-projects=]].

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-project-settings
((org-agenda-overriding-header "Projects")
 (org-agenda-skip-function 'rrogg/skip-non-projects)
 (org-tags-match-list-sublevels 'indented))
#+end_src

***** Project Next Tasks

Tasks in =NEXT= state, that move a project towards its goal, are listed in this
section. If a task is displayed here, it can be worked on right away.

#+begin_src emacs-lisp :tangle no :noweb yes :noweb-ref my-agenda-cmd-project-next
(<<my-agenda-cmd-project-next-cmd-match>>
      <<my-agenda-cmd-project-next-settings>>)
#+end_src

Given by the section name, only =NEXT= stated are valid.

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-project-next-cmd-match
tags-todo "/!-HOLD-CANCELLED-WAITING-CALL"
#+end_src

[[id:b5c5c889-06c7-46b2-a89d-32327610f5a9][Standalone tasks]] are excluded from this section. Those are tasks that are
independent from a project and have their own section.
The skip function is [[id:61741020-afa3-43ed-8db2-ba936490c0cd][=rrogg/skip-projects-standalone=]].

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-project-next-settings
((org-agenda-overriding-header "Project Next Tasks")
 (org-agenda-skip-function 'rrogg/skip-projects-standalone))
#+end_src

***** Standalone Tasks
:PROPERTIES:
:ID:       b5c5c889-06c7-46b2-a89d-32327610f5a9
:END:

Independent tasks, meaning tasks that are not contributing towards a common goal
within a project, are displayed separately.
All headings under this section must have a todo-state. Therefore the agenda
command =tags-todo= is fitting, because it automatically skips non-task
headings.

#+begin_src emacs-lisp :tangle no :noweb yes :noweb-ref my-agenda-cmd-standalone
(<<my-agenda-cmd-standalone-cmd-match>>
      <<my-agenda-cmd-standalone-settings>>)
#+end_src

All tasks are matched against the following todo-states or tags:
- Skip tasks tagged =:REFILE:= - those are gathered in section =Headings to
  Refile=.
- Skip =CANCELLED= tasks - those are gathered elsewhere.
- Skip =CALL= tasks - those are only shown in the agenda.

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-standalone-cmd-match
tags-todo "-REFILE/!-CANCELLED-CALL-WAITING"
#+end_src

The remaining candidates to display still contain projects and project tasks.
Those need to be skipped. A function can be assigned to
=org-agenda-skip-function= in order to do this step.
The skip function should return =nil= in case the current match should not be
skipped. In case the match should be skipped, the return value must be a
position from which the search for the next match should be continued.

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-standalone-settings
((org-agenda-overriding-header "Standalone Tasks")
 (org-agenda-skip-function 'rrogg/skip-project-tasks))
#+end_src

***** Planned Projects
:PROPERTIES:
:ID:       a23e5e51-6634-4807-a5db-5d772c8ea1b3
:END:

Projects that are not completely planned and need some more thought before they
can be started have their own section. I can't work on tasks for those projects
right now. But still, I want to have them visible in order to drive me to
complete the planning.

#+begin_src emacs-lisp :tangle no :noweb yes :noweb-ref my-agenda-cmd-project-plan
(<<my-agenda-cmd-project-plan-cmd-match>>
      <<my-agenda-cmd-project-plan-settings>>)
#+end_src

All projects to be considered in this section are in =PLANNING= state.

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-project-plan-cmd-match
tags-todo "/!-HOLD-CANCELLED+PLANNING"
#+end_src

The skip function is the same as for regular projects
([[id:6faa31dc-43a0-447a-88d0-fffbe14a3cb0][=rrogg/skip-non-projects=]]).

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-project-plan-settings
((org-agenda-overriding-header "Planned Projects")
 (org-agenda-skip-function 'rrogg/skip-non-projects))
#+end_src

***** Waiting and On-Hold Tasks

All tasks that I am waiting on or that I put on hold for now, are listed
here. This sections prevents that those tasks are forgotten and acts as a
reminder to reinvestigate why they are blocked.

#+begin_src emacs-lisp :tangle no :noweb yes :noweb-ref my-agenda-cmd-waiting
(<<my-agenda-cmd-waiting-cmd-match>>
      <<my-agenda-cmd-waiting-settings>>)
#+end_src

=WAITING= and =HOLD= states are considered to be shown here.

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-waiting-cmd-match
tags-todo "/!-CANCELLED+WAITING|+HOLD"
#+end_src

Everything that is not a task will be skipped by [[id:25074132-89d0-4e89-98bd-be8e34637b75][=rrogg/skip-non-tasks=]].

#+begin_src emacs-lisp :tangle no :noweb-ref my-agenda-cmd-waiting-settings
((org-agenda-overriding-header "Waiting and On-Hold Tasks")
 (org-agenda-skip-function 'rrogg/skip-non-tasks))
#+end_src

**** My Work Agenda

#+begin_src emacs-lisp :tangle no :noweb yes :noweb-ref my-work-agenda
'(<<my-work-agenda-key-desc>>
  (<<my-agenda-cmd-agenda>>
   <<my-agenda-cmd-refile>>
   <<my-agenda-cmd-stuck-project>>
   <<my-agenda-cmd-project>>
   <<my-agenda-cmd-project-next>>
   <<my-agenda-cmd-standalone>>
   <<my-agenda-cmd-project-plan>>
   <<my-agenda-cmd-waiting>>)
;  ((org-agenda-files '("~/org/refile.org" "~/org/agenda-settings.org" "~/org/private/private.org" "~/org/family/family.org")))
  ((org-agenda-time-grid
    '((daily today require-timed)
      (0900 1000 1100 1200 1300
	    1400 1500 1600 1700)
      " ....." "-----------------"))))
#+end_src

The agenda can be called by pressing =key= when on the agenda dispatcher. The
complete key command is =C-c a w=.
A description of the view is passed to the agenda dispatcher via =desc=.

#+begin_src emacs-lisp :tangle no :noweb-ref my-work-agenda-key-desc
"w" "My Work Agenda"
#+end_src

**** My Private Agenda

#+begin_src emacs-lisp :tangle no :noweb yes :noweb-ref my-private-agenda
'(<<my-private-agenda-key-desc>>
  (<<my-agenda-cmd-agenda>>
   <<my-agenda-cmd-refile>>
   <<my-agenda-cmd-stuck-project>>
   <<my-agenda-cmd-project>>
   <<my-agenda-cmd-project-next>>
   <<my-agenda-cmd-standalone>>
   <<my-agenda-cmd-project-plan>>
   <<my-agenda-cmd-waiting>>)
  ((org-agenda-files '("~/org/refile.org" "~/org/agenda-settings.org" "~/org/private/private.org" "~/org/family/family.org"))))
#+end_src

The agenda can be called by pressing =key= when on the agenda dispatcher. The
complete key command is =C-c a p=.
A description of the view is passed to the agenda dispatcher via =desc=.

#+begin_src emacs-lisp :tangle no :noweb-ref my-private-agenda-key-desc
"p" "My Private Agenda"
#+end_src

**** Functions for Agenda Building

***** Skip Functions

These functions are used for skipping headings that have been matched during
creating of the agenda.
The expected return values are:
- =position=: In case of identification of a heading that should be skipped, the
  position from where to continue is the return value.
- =nil=: In case of a heading that should not be skipped.

****** Skip Projects and Project Tasks
:PROPERTIES:
:ID:       4743e8ba-4c6c-459b-9c26-a669ad843dc8
:END:

First of, =save-restriction= saves the current buffer’s restrictions when it is
entered and restores them when it is exited.
Then potential narrowing of the buffer gets removed with =widen=.
A local binding for the variable =end-of-subtree= is created using =let=. This
binding will only be in effect within the body of the =let= statement.
The variable =end-of-subtree= holds the position of the end of the subtree
visited by =org-end-of-subtree=. This is possible to do so because it is
encapsulated in a =save-excursion= special form. This saves point and current
buffer, executes =org-end-of-subtree= and restores the previous state of point
and buffer.
The body of =let= is a conditional control structure =cond=. The body of the
first condition successfully is returned. If non succeeds the return value is
=nil=.
The headings will be checked against [[id:4564159d-6e4b-43a2-9ec5-7650d25501c7][=rrogg/is-project-p=]]. If this functions
returns =t=, the complete subtree will be skipped.

#+begin_src emacs-lisp
(defun rrogg/skip-project-tasks ()
  "Skip org-headings that are part of a project.
If heading should be skipped, return position of end of subtree to continue searching.
Return nil in case the heading should not be skipped."
  (save-restriction
    (widen)
    (let ((end-of-subtree (save-excursion (org-end-of-subtree t))))
      (cond
       ((rrogg/is-project-p)
        end-of-subtree)
       (t
        nil)))))
#+end_src

****** Skip Non-Projects
:PROPERTIES:
:ID:       6faa31dc-43a0-447a-88d0-fffbe14a3cb0
:END:

This function follows the same structure as [[id:4743e8ba-4c6c-459b-9c26-a669ad843dc8][=rrogg/skip-project-tasks=]].
Headings will be checked against [[id:10e7b990-3bb5-4a81-8015-d0b7c59fa95c][=rrogg/is-stuck-project-p=]] and
[[id:4564159d-6e4b-43a2-9ec5-7650d25501c7][=rrogg/is-project-p=]].

#+begin_src emacs-lisp
(defun rrogg/skip-non-projects ()
  "Skip org-headings that are not projects.
If heading should be skipped, return position of end of subtree to continue searching.
Return nil in case the heading should not be skipped."
  (save-restriction
    (widen)
    (let ((end-of-subtree (save-excursion (org-end-of-subtree t))))
      (cond
       ((rrogg/is-stuck-project-p)
        end-of-subtree)
       ((rrogg/is-project-p)
        nil)
       (t
        end-of-subtree)))))
#+end_src

****** Skip Non-Project Tasks
:PROPERTIES:
:ID:       65df0c1d-cc31-4823-9153-a0362b0257f9
:END:

Similar structure to the previous skip functions.

#+begin_src emacs-lisp
(defun rrogg/skip-non-project-tasks ()
  "Skip org-headings that are projects, subproject tasks or standalone tasks.
If heading should be skipped, return position of end of subtree to continue searching.
Return nil in case the heading should not be skipped."
  (save-restriction
    (widen)
    (let ((end-of-subtree (save-excursion (org-end-of-subtree t)))
          (next-headline (save-excursion (or (outline-next-heading) (point-max)))))
      (cond
       ((rrogg/is-project-p)
        next-headline)
       ((and (rrogg/is-project-task-p)
             (equal (org-get-todo-state) "NEXT"))
        end-of-subtree)
       ((not (rrogg/is-project-task-p))
        end-of-subtree)
       (t
        nil)))))
#+end_src

****** Skip Projects and Standalone Tasks
:PROPERTIES:
:ID:       61741020-afa3-43ed-8db2-ba936490c0cd
:END:

Similar structure to the previous skip functions.

#+begin_src emacs-lisp
(defun rrogg/skip-projects-standalone ()
  "Skip org-headings that are projects or standalone tasks.
If heading should be skipped, return position of end of subtree to continue searching.
Return nil in case the heading should not be skipped."
  (save-restriction
    (widen)
    (let ((next-headline (save-excursion (or (outline-next-heading) (point-max)))))
      (cond
       ((rrogg/is-project-p)
        next-headline)
       ((and (rrogg/is-task-p) (not (rrogg/is-project-task-p)))
        next-headline)
       ((rrogg/is-project-planning-task-p)
        next-headline)
       (t
        nil)))))
#+end_src

****** Skip Non-Stuck-Projects
:PROPERTIES:
:ID:       8dc94898-0f38-4aee-b1be-db569f3879a3
:END:

Similar structure to the previous skip functions.

#+begin_src emacs-lisp
(defun rrogg/skip-non-stuck-projects ()
  "Skip org-headings that are projects and not stuck.
If heading should be skipped, return position of end of subtree to continue searching.
Return nil in case the heading should not be skipped."
  (save-restriction
    (widen)
    (let ((next-headline (save-excursion (or (outline-next-heading) (point-max)))))
      (cond
       ((rrogg/is-project-planning-task-p)
        next-headline)
       ((rrogg/is-project-hold-task-p)
        next-headline)
       ((rrogg/is-stuck-project-p)
        nil)
       (t
        next-headline)))))
#+end_src

****** Skip Non-Tasks
:PROPERTIES:
:ID:       25074132-89d0-4e89-98bd-be8e34637b75
:END:

Similar structure to the previous skip functions.

#+begin_src emacs-lisp
(defun rrogg/skip-non-tasks ()
  "Skip org-headings that are projects or subprojects.
If heading should be skipped, return position of end of subtree to continue searching.
Return nil in case the heading should not be skipped."
  (save-restriction
    (widen)
    (let ((next-headline (save-excursion (or (outline-next-heading) (point-max)))))
      (cond
       ((rrogg/is-task-p)
        nil)
       (t
        next-headline)))))
#+end_src

***** Identification Functions

The following functions are used to identify what kind of org-heading or task an
entry is.
Return value is either =t= or =nil=.

****** Identify Projects
:PROPERTIES:
:ID:       4564159d-6e4b-43a2-9ec5-7650d25501c7
:END:

Current buffer's restrictions are saved via =save-restriction= and restored when
the function is exited.
Then potential narrowing of the buffer gets removed with =widen=.
Three local bindings for variables are needed in order to determine if the tasks
is a project:
- =end-of-subtree=: Holds the position of the end of the subtree visited by
  =org-end-of-subtree=.
- =is-task=: Checks if org-heading has a todo keyword, returns boolean.
- =has-subtask=: Boolean, default value is =nil=.
Because this function examines the org-headings coming after the current one,
point is moved one line forward.
The following =while= control loop searches for the next org-heading and sets
the variable =has-subtask= to =t= if the org-heading contains a todo keyword.
The return value is =t= if both of =is-task= and =has-subtask= are =t=.

#+begin_src emacs-lisp
(defun rrogg/is-project-p ()
  "A task with a subtask is a project."
  (save-restriction
    (widen)
    (let ((end-of-subtree (save-excursion (org-end-of-subtree t)))
          (is-task (member (org-get-todo-state) org-todo-keywords-1))
          (has-subtask))
      (save-excursion
        (forward-line 1)
        (while (and (< (point) end-of-subtree)
                    (re-search-forward "^\*+ " end-of-subtree t)
                    (not has-subtask))
          (when (member (org-get-todo-state) org-todo-keywords-1)
            (setq has-subtask t))))
      (and is-task has-subtask))))
#+end_src

****** Identify Stuck Projects
:PROPERTIES:
:ID:       10e7b990-3bb5-4a81-8015-d0b7c59fa95c
:END:

Similar structure to the previous identify function.

#+begin_src emacs-lisp
(defun rrogg/is-stuck-project-p ()
  "A task without a subtask in NEXT state is a stuck project."
  (save-restriction
    (widen)
    (if (rrogg/is-project-p)
        (let ((end-of-subtree (save-excursion (org-end-of-subtree t)))
              (has-next-subtask))
          (save-excursion
            (forward-line 1)
            (while (and (< (point) end-of-subtree) (re-search-forward "^\*+ NEXT\\|CALL " end-of-subtree t) (not has-next-subtask))
              (setq has-next-subtask t)))
          (if has-next-subtask
              nil
            t))
      nil)))
#+end_src

****** Identify Tasks
:PROPERTIES:
:ID:       4b9cc45a-ced1-4b52-804e-277fb0d97166
:END:

Similar structure to the previous identify functions.

#+begin_src emacs-lisp
(defun rrogg/is-task-p ()
  "Check if task has no subtask."
  (save-restriction
    (widen)
    (let ((end-of-subtree (save-excursion (org-end-of-subtree t)))
          (is-task (member (org-get-todo-state) org-todo-keywords-1))
          (has-subtask))
      (save-excursion
        (forward-line 1)
        (while (and (< (point) end-of-subtree)
                    (re-search-forward "^\*+ " end-of-subtree t)
                    (not has-subtask))
          (when (member (org-get-todo-state) org-todo-keywords-1)
            (setq has-subtask t))))
      (and is-task (not has-subtask)))))
#+end_src

****** Identify Project Task
:PROPERTIES:
:ID:       898ba890-792b-4d57-a67e-255e88f5ef68
:END:

Similar structure to the previous identify functions.

#+begin_src emacs-lisp
(defun rrogg/is-project-task-p ()
  "Check if task is part of a project."
  (save-restriction
    (widen)
    (let ((parent-task (save-excursion (org-back-to-heading t) (point))))
      (save-excursion
        (rrogg/find-parent-task)
        (if (equal (point) parent-task)
            nil
          t)))))
#+end_src

****** Identify Project Planning Task

Similar structure to the previous identify functions.

#+begin_src emacs-lisp
(defun rrogg/is-project-planning-task-p ()
  "Check if task is part of a project in planning state."
  (save-restriction
    (widen)
    (let ((parent-task (save-excursion (org-back-to-heading t) (point))))
      (save-excursion
        (rrogg/find-parent-planning-task)
        (if (equal (point) parent-task)
            nil
          t)))))
#+end_src
****** Identify Project Hold Task

Similar structure to the previous identify functions.

#+begin_src emacs-lisp
(defun rrogg/is-project-hold-task-p ()
  "Check if task is part of a project in hold state."
  (save-restriction
    (widen)
    (let ((parent-task (save-excursion (org-back-to-heading t) (point))))
      (save-excursion
        (rrogg/find-parent-hold-task)
        (if (equal (point) parent-task)
            nil
          t)))))
#+end_src

***** Search Functions

The following functions are used to search for specific org-headings or tasks.
Return value is the position of point at the beginning of the heading or =nil=.

****** Find Parent Task
:PROPERTIES:
:ID:       1e618736-8432-4213-84cf-94b9835a8ede
:END:

#+begin_src emacs-lisp
(defun rrogg/find-parent-task ()
  "Move point to the parent task of a task."
  (save-restriction
    (widen)
    (let ((parent-task (save-excursion (org-back-to-heading t) (point))))
      (while (org-up-heading-safe)
        (when (member (org-get-todo-state) org-todo-keywords-1)
          (setq parent-task (point))))
      (goto-char parent-task))))
#+end_src

****** Find Parent Planning Task

#+begin_src emacs-lisp
(defun rrogg/find-parent-planning-task ()
  "Move point to the parent planning task of a task."
  (save-restriction
    (widen)
    (let ((parent-task (save-excursion (org-back-to-heading t) (point))))
      (while (org-up-heading-safe)
        (when (equal (org-get-todo-state) "PLANNING")
          (setq parent-task (point))))
      (goto-char parent-task))))
#+end_src

****** Find Parent Hold Task

#+begin_src emacs-lisp
(defun rrogg/find-parent-hold-task ()
  "Move point to the parent hold task of a task."
  (save-restriction
    (widen)
    (let ((parent-task (save-excursion (org-back-to-heading t) (point))))
      (while (org-up-heading-safe)
        (when (equal (org-get-todo-state) "HOLD")
          (setq parent-task (point))))
      (goto-char parent-task))))
#+end_src

*** Show Small Icons in Agenda View

Some agenda entries belonging to a certain category have a small 16 x 16 pixel
icon assigned to them. If the entries category has no icon assigned, it is
displayed 16 pixels further right.

The icons are stored in =~/templates_labels/icons/=.

#+begin_src emacs-lisp
(setq org-agenda-category-icon-alist
      '(("\\(Holiday\\|Vacation\\)" "~/templates_labels/icons/holiday.png" nil nil :ascent center)
        ("Anniv." "~/templates_labels/icons/anniversary.png" nil nil :ascent center)
        ("Spec. Date" "~/templates_labels/icons/specialdate.png" nil nil :ascent center)
        ("Time" "~/templates_labels/icons/time.png" nil nil :ascent center)
        ("Marriage" "~/templates_labels/icons/marriage.gif" nil nil :ascent center)
        ("Love" "~/templates_labels/icons/love.png" nil nil :ascent center)
        ("Mourning" "~/templates_labels/icons/mourning.png" nil nil :ascent center)
        (".*" '(space . (:width (16))))))
#+end_src

* Outro
** Final Spurt

This is the end of =rrogg-emacs.org=. Let's see how much time it took to load
all of the shenanigans. Write the result to the =Messages= buffer.

#+begin_src emacs-lisp
(message "→★ Finished loading rrogg-emacs in %.2fs" (float-time (time-subtract (current-time) rrogg-emacs-start-time)))
#+end_src
