#+TITLE: RROGG-EMACS - AN EMACS CONFIGURATION
#+PROPERTY: header-args :result silent :tangle "~/.emacs.d/init.el" :eval no-export :comments org

* Intro
** Track Loading Time of rrogg-emacs

Starting Emacs has to be as quick as possible. In order to evaluate the time it
takes to load =rrogg-emacs.org=, someone has to blow the whistle and start the
stopwatch.

#+begin_src emacs-lisp
(defvar rrogg-emacs-start-time (current-time) "Time when rrogg-emacs was started")
#+end_src

* Maximize Frame

The Emacs frame is maximized at all times to make use of every pixel on the
screen.

#+begin_src emacs-lisp
(toggle-frame-maximized)
#+end_src

* Disable GUI Bar Components

Display no GUI components other than the =modline=.

#+begin_src emacs-lisp
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
#+end_src

* Hide Welcome Screen and Empty =*scratch*=

Emacs shows a splash screen at startup from which one can easily get to the
tutorial. While helpful in the beginning, this screen gets abdicable with
time. Therefore it's disabled.
Emacs also automatically loads a buffer called =*scratch*=, which serves as a
place to try out emacs lisp code or to type out some ideas. This is very helpful
as one doesn't have to think about creating a new file for every unrelated
thought. The welcome message isn't needed, so it gets disabled.

#+begin_src emacs-lisp
(setq inhibit-splash-screen t)
(setq initial-scratch-message nil)
#+end_src

* Display Current Time and Date

While I use Emacs exclusively full screen, no user interface elements like
taskbars are visible that could offer space for useful information like the
current time and date.

A solution for that is the builtin =display-time-mode=.
Once enabled, this mode displays time and date in the modeline.

A caveat of placing that info on the modeline, is information duplication. The
time will be shown on the modeline of every open buffer.
Ideally there would be only one "universal bar" that holds such universal info.

#+begin_src emacs-lisp
(setq display-time-format "%a %e %b, %H:%M")
(setq display-time-interval 60)
(setq display-time-default-load-average nil)
(add-hook 'after-init-hook #'display-time-mode)
#+end_src

* Wrap Lines at a Reasonable Width

Long lines of text are wrapped at a width of 80 characters. In order to leave
long code lines untouched, automatic line wrap is only active in =text-mode= and
modes which inherit from it, like =org-mode=.

#+begin_src emacs-lisp
(setq-default fill-column 80)
(add-hook 'text-mode-hook 'auto-fill-mode)
#+end_src

* Force a Sane Coding System

The only way to go in regards of a sane coding system for text files is utf-8.
It has to be the the default when ever possible. This provides maximal
portability and readability across operation systems and applications.
Also the Unix way of adding a new line into a text file has to be the
default. DOS uses carriage return and line feed ("\r\n") as a line ending, where
Unix uses just line feed ("\n").

#+begin_src emacs-lisp
(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8-unix)
(set-charset-priority 'unicode)
(setq default-process-coding-system '(utf-8-unix . utf-8-unix))
(setq locale-coding-system 'utf-8)
#+end_src

* Save Commands Across Sessions

Emacs doesn't have a persistent command history by default. The build-in history
gets resetted with every new Emacs session. The package =savehist= implements a
session independent history.

#+begin_src emacs-lisp
(setq savehist-file (locate-user-emacs-file "savehist"))
(setq history-length 10000)
(setq history-delete-duplicates t)
(setq savehist-save-minibuffer-history t)
(add-hook 'after-init-hook #'savehist-mode)
#+end_src

* Unique Buffer Names

Dealing with multiple files of identical name from different directories is
sometimes confusing. Working with multiple main.cpp files is one example.
The builtin =uniquify= package makes it easier to identify the files in such
scenarios.

#+begin_src emacs-lisp
(setq uniquify-buffer-name-style 'forward)
(setq uniquify-strip-common-suffix t)
(setq uniquify-after-kill-buffer-p t)
#+end_src

* Managing Buffers

By default =C-x C-b= calls the Buffer List. IBuffer is an alternative with more
functionality when it comes to manipulate the buffer list and switching
buffers.
It can filter the buffer list in various ways, execute =occur= or
=query-replace= commands straight from the list and much more.
Check =C-h m= while in IBuffer and read it's help.
A demonstration of it's capabilities can be observed in Protesilaos Stavrou's
video [[http://192.168.178.110:3000/watch?v=6KN_oSLFf-k][Emacs: introduction to IBUFFER]].

The format of IBuffer is changed so that the name column gets elided after 40
characters instead of the default 16 to make longer buffer names readable.

#+begin_src emacs-lisp
(setq ibuffer-expert t)
(setq ibuffer-display-summary nil)
(setq ibuffer-use-other-window nil)
(setq ibuffer-show-empty-filter-groups nil)
(setq ibuffer-movement-cycle nil)
(setq ibuffer-default-sorting-mode 'filename/process)
(setq ibuffer-use-header-line t)
(setq ibuffer-default-shrink-to-minimum-size nil)
(setq ibuffer-saved-filter-groups nil)
(setq ibuffer-old-time 48)
(setq ibuffer-formats
        '((mark modified read-only locked " "
                (name 40 40 :left :elide)
                " "
                (size 9 -1 :right)
                " "
                (mode 16 16 :left :elide)
                " " filename-and-process)
          (mark " "
                (name 16 -1)
                " " filename)))
(define-key global-map (kbd "C-x C-b") #'ibuffer)
#+end_src

* Package Management

Most extensions to Emacs can be loaded from archives, which are accessible via
Emacs' very own package manager =package.el=. To use this feature, =package.el=
needs to know, which archives it should use.
Out of the box, Emacs includes the =GNU ELPA= archive. It contains packages
conform with the terms of the Free Software Foundation.

To handle the package management, =package.el= has to be required early.

#+begin_src emacs-lisp
(require 'package)
#+end_src

Installing external packages that can be found in one of the Emacs Lisp Package
Archives is not an automatic process by default. The variable
=rrogg-emacs-autoinstall= has to be true in order to enable autoinstall.
A list of packages that =rrogg-emacs= tries to configure but are not installed will
be populated by the macro =rrogg-emacs-elpa-package=.
Those packages can be installed by running the function
=rrogg-emacs-install-missing-packages=.

#+begin_src emacs-lisp
(defvar rrogg-emacs-autoinstall nil
  "Control if `rrogg-emacs-elpa-package' should install packages automatically.
A value of nil will disable automatic installation of missing packages.
A non-nil value will install missing packages automatically without asking the user for consent.")

(defvar rrogg-emacs-missing-packages-list nil
  "List of package names that are required in rrogg-emacs, but currently not installed.")

(defun rrogg-emacs-install-missing-packages ()
  "Install all packages from the `rrogg-emacs-missing-packages-list'."
  (interactive)
  (when (yes-or-no-p (format "Try to install %d packages?"
                             (length rrogg-emacs-missing-packages-list)))
    (package-refresh-contents)
    (mapc (lambda (package)
            (unless (package-installed-p package)
              (package-install package)))
          rrogg-emacs-missing-packages-list)))
#+end_src

Packages that are not shipped with Emacs or are not additions from me for
standard packages, are loaded and configured via =rrogg-emacs-elpa-package=. If
those have not been installed yet, they are marked for installation by
explicitly running =rrogg-emacs-install-missing-packages= or installed
automatically if =rrogg-emacs-autoinstall= is non-nil. If the package is
installed already, it gets loaded and configured with the settings passed to the
macro.

#+begin_src emacs-lisp
(defmacro rrogg-emacs-elpa-package (package &rest body)
  "Set up PACKAGE installed from one of the `package-archives' with the rest BODY.
PACKAGE is a quoted symbol ('package) and BODY consists of balanced expressions (setq variable value)."
  `(progn
     (when (and rrogg-emacs-autoinstall
                (not (package-installed-p ,package)))
       (package-install ,package))
     (if (require ,package nil 'noerror)
         (progn ,@body)
       (display-warning 'rrogg-emacs (format "Loading package `%s' failed" ,package) :warning)
       (add-to-list 'rrogg-emacs-missing-packages-list ,package)
       (display-warning 'rrogg-emacs (format "Run `rrogg-emacs-install-missing-packages' to install all missing packages listed in `rrogg-emacs-missing-packages-list'") :warning))))
#+end_src

* Outro
** Final Spurt

This is the end of =rrogg-emacs.org=. Let's see how much time it took to load
all of the shenanigans. Write the result to the =Messages= buffer.

#+begin_src emacs-lisp
(message "→★ Finished loading rrogg-emacs in %.2fs" (float-time (time-subtract (current-time) rrogg-emacs-start-time)))
#+end_src
