#+TITLE: RROGG-EMACS - AN EMACS CONFIGURATION
#+PROPERTY: header-args :result silent :tangle "~/.emacs.d/init.el" :eval no-export :comments org

* Intro
** Track Loading Time of rrogg-emacs

Starting Emacs has to be as quick as possible. In order to evaluate the time it
takes to load =rrogg-emacs.org=, someone has to blow the whistle and start the
stopwatch.

#+begin_src emacs-lisp
(defvar rrogg-emacs-start-time (current-time) "Time when rrogg-emacs was started")
#+end_src

* Maximize Frame

The Emacs frame is maximized at all times to make use of every pixel on the
screen.

#+begin_src emacs-lisp
(toggle-frame-maximized)
#+end_src

* Disable GUI Bar Components

Display no GUI components other than the =modline=.

#+begin_src emacs-lisp
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
#+end_src

* Hide Welcome Screen and Empty =*scratch*=

Emacs shows a splash screen at startup from which one can easily get to the
tutorial. While helpful in the beginning, this screen gets abdicable with
time. Therefore it's disabled.
Emacs also automatically loads a buffer called =*scratch*=, which serves as a
place to try out emacs lisp code or to type out some ideas. This is very helpful
as one doesn't have to think about creating a new file for every unrelated
thought. The welcome message isn't needed, so it gets disabled.

#+begin_src emacs-lisp
(setq inhibit-splash-screen t)
(setq initial-scratch-message nil)
#+end_src

* Display Current Time and Date

While I use Emacs exclusively full screen, no user interface elements like
taskbars are visible that could offer space for useful information like the
current time and date.

A solution for that is the builtin =display-time-mode=.
Once enabled, this mode displays time and date in the modeline.

A caveat of placing that info on the modeline, is information duplication. The
time will be shown on the modeline of every open buffer.
Ideally there would be only one "universal bar" that holds such universal info.

#+begin_src emacs-lisp
(setq display-time-format "%a %e %b, %H:%M")
(setq display-time-interval 60)
(setq display-time-default-load-average nil)
(add-hook 'after-init-hook #'display-time-mode)
#+end_src

* Wrap Lines at a Reasonable Width

Long lines of text are wrapped at a width of 80 characters. In order to leave
long code lines untouched, automatic line wrap is only active in =text-mode= and
modes which inherit from it, like =org-mode=.

#+begin_src emacs-lisp
(setq-default fill-column 80)
(add-hook 'text-mode-hook 'auto-fill-mode)
#+end_src

* Force a Sane Coding System

The only way to go in regards of a sane coding system for text files is utf-8.
It has to be the the default when ever possible. This provides maximal
portability and readability across operation systems and applications.
Also the Unix way of adding a new line into a text file has to be the
default. DOS uses carriage return and line feed ("\r\n") as a line ending, where
Unix uses just line feed ("\n").

#+begin_src emacs-lisp
(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8-unix)
(set-charset-priority 'unicode)
(setq default-process-coding-system '(utf-8-unix . utf-8-unix))
(setq locale-coding-system 'utf-8)
#+end_src

* Save Commands Across Sessions

Emacs doesn't have a persistent command history by default. The build-in history
gets resetted with every new Emacs session. The package =savehist= implements a
session independent history.

#+begin_src emacs-lisp
(setq savehist-file (locate-user-emacs-file "savehist"))
(setq history-length 10000)
(setq history-delete-duplicates t)
(setq savehist-save-minibuffer-history t)
(add-hook 'after-init-hook #'savehist-mode)
#+end_src

* Outro
** Final Spurt

This is the end of =rrogg-emacs.org=. Let's see how much time it took to load
all of the shenanigans. Write the result to the =Messages= buffer.

#+begin_src emacs-lisp
(message "→★ Finished loading rrogg-emacs in %.2fs" (float-time (time-subtract (current-time) rrogg-emacs-start-time)))
#+end_src
